### PR TITLE
minor typo in README

### PR DESCRIPTION
**Pull request by privong**
Just fixing a small typo in the suggested invocation for the web server.

### CODE REVIEW

**Comment by waldyrious** [comment]
That's the actual name of the file: [arbtt-serve.py](https://github.com/rejuvyesh/arbtt-graph/blob/master/arbtt-serve.py)

**Comment by privong** [comment]
@waldyrious Yea, I fixed where it had said `arbtt-server.py` (extra "r") instead of `arbtt-serve.py`

**Comment by rejuvyesh** [comment]
Thanks!

**Comment by waldyrious** [comment]
D'oh! I read the diff backwards :) sorry for the noise.

**Pull request merged**
